version: '2'
services:
    yaldaygateway-mongodb:
        container_name: yaldaygateway-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/YaldayGateway/mongodb/:/data/db/
